Repository chimdie/shorttiee, pull requests merged in 2024-12, with the labels that each got.

#34 fix: sidebar active state on hover
  host/src/components/Sidebar/app-sidebar.tsx
  host/src/components/ui/button.tsx
  host/src/components/ui/carousel.tsx
  host/src/pages/Dashboard/Shortlet/shortletDetails.tsx
Labels: bug

#35 Feat/UI/settings
  host/src/App.tsx
  host/src/components/DeleteAccountModal.tsx
  host/src/components/Sidebar/app-sidebar.tsx
  host/src/components/Sidebar/sidebarMenuItem.ts
  host/src/pages/Dashboard/Notification/index.tsx
  host/src/pages/Dashboard/Payments/index.tsx
  host/src/pages/Dashboard/Settings/index.tsx
  host/src/types/routes.ts
Labels: enhancement

#28 listings, category and facility
  server/.gitignore
  server/db/migrations/20241120145157_create_listings.sql
  server/db/migrations/20241123140022_create_categories.sql
  server/db/migrations/20241128133409_create_files.sql
  server/db/migrations/20241202220615_create_facilities.sql
  server/db/migrations/20241203205409_create_listings_facilities.sql
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/config/services.config.ts
  server/src/config/upload/hash-storage.upload.ts
  server/src/config/upload/index.ts
  server/src/controllers/auth.ctl.ts
  server/src/controllers/category.ctl.ts
  server/src/controllers/facility.ctl.ts
  server/src/controllers/file.ctl.ts
  server/src/controllers/listing.ctl.ts
  server/src/db/category.db.ts
  server/src/db/facility-and-listing.db.ts
  server/src/db/facility.db.ts
  server/src/db/file.db.ts
  server/src/db/listing.db.ts
  server/src/docs/auth.docs.ts
  server/src/docs/category.docs.ts
  server/src/docs/facility.docs.ts
  server/src/docs/file.docs.ts
  server/src/docs/index.ts
  server/src/docs/listings.docs.ts
  server/src/docs/users.docs.ts
  server/src/dto/category.dto.ts
  server/src/dto/env.dto.ts
  server/src/dto/facility.dto.ts
  server/src/dto/file.dto.ts
  server/src/dto/listings.dto.ts
  server/src/dto/util.dto.ts
  server/src/index.ts
  server/src/middlewares/auth.middleware.ts
  server/src/middlewares/validator.middleware.ts
  server/src/routes/category.routes.ts
  server/src/routes/docs.routes.ts
  server/src/routes/facility.routes.ts
  server/src/routes/files.routes.ts
  server/src/routes/index.ts
  server/src/routes/listing.routes.ts
  server/src/tests/auth.test.ts
  server/src/tests/category.test.ts
  server/src/tests/facility.test.ts
  server/src/tests/file.test.ts
  server/src/tests/helper.ts
  server/src/tests/listings.test.ts
  server/src/tests/seed.ts
  server/src/types/index.d.ts
  server/src/types/utils.d.ts
  server/src/utils/auth-token.ts
  server/src/utils/fn-result.ts
  server/src/utils/otp.ts
Labels: enhancement

#40 fix github ci setup
  .github/workflows/server.ci.yml
Labels: bug

#45 Feat/UI/reservation
  host/src/App.tsx
  host/src/components/Reservations/accept-reservation-modal.tsx
  host/src/components/Reservations/confirmed-reservation.tsx
  host/src/components/Reservations/incoming-reservation.tsx
  host/src/components/Reservations/reject-reservation-modal.tsx
  host/src/components/Reservations/rejected-reservation.tsx
  host/src/components/Sidebar/nav-user.tsx
  host/src/components/Sidebar/sidebarMenuItem.ts
  host/src/dummyData/shortlet.ts
  host/src/layouts/Dashboard.layout.tsx
  host/src/pages/Dashboard/Reservation/index.tsx
  host/src/schema/reservation.schema.ts
  host/src/types/routes.ts
Labels: enhancement

#49 Docs scalar-ui
  server/package-lock.json
  server/package.json
  server/src/config/docs.config.ts
  server/src/public/js/api-reference.js
  server/src/routes/docs.routes.ts
  server/tsconfig.json
Labels: documentation, server

#53 feat: add image as url #26
  host/src/components/Shortlet/add-shortlet-modal.tsx
  host/src/schema/shortlet.schema.ts
Labels: enhancement
